---
title: "Weekend Homework - Text Mining"
output: html_document
---



1 MVP
Using the dataset austen_books() from the package janeaustenr:

```{r}
library(dplyr)
library(tidyr)
library(tidytext)
library(ggwordcloud)
library(hcandersenr)
library(janeaustenr)
```


Find the most common words in both Pride & Prejudice and Sense & Sensibility.
```{r}
titles <- c("Pride and Prejudice", "Sense and Sensibility")
books <- list(prideprejudice, sensesensibility)
```
```{r}
books <- purrr::map_chr(books, paste, collapse = " ")
str(books)
```
```{r}
pride_and_sensibility <- tibble(
  title = titles,
  text = books
) %>%
  unnest_tokens(word, text)

head(pride_and_sensibility)
```
```{r}
pride_and_sensibility %>%
  count(word) %>%
  arrange(desc(n))
```
Find the most common words in both Pride & Prejudice and Sense & Sensibility, not including stop words.
```{r}
pride_and_sensibility %>%
  anti_join(stop_words) %>%
  count(word, sort = T)
```


Find the most common sentiment words in both Pride & Prejudice and Sense & Sensibility.
```{r}
pride_and_sensibility %>%
  inner_join(get_sentiments("bing")) %>%
  count(sentiment)
```
```{r}
positive_sentiment <- pride_and_sensibility %>%
  inner_join(get_sentiments("bing"))
```
```{r}
positive_sentiment %>%
  filter(sentiment == "positive") %>%
  count(word, sort = TRUE)
```

